Proj 1 vector operations
MAGLeb/made-cpp-2020-hw pull request #3
Opened 2020-10-06 17:31 UTC by MAGLeb

Если сможете подсказать, что означает расширение файлов h - буду признателен. Конечно я нашел ответ в интеренете, но куда приятнее услышать разверный ответ на русском.

2020-10-17 15:01 UTC, SweetWeakness commented
> Если сможете подсказать, что означает расширение файлов h - буду признателен. Конечно я нашел ответ в интеренете, но куда приятнее услышать разверный ответ на русском.

header файл, нужны для объявления функций, классов и тд (одно из основных применений)
например, хочу написать класс Point
в Point.h создаю класс и объявляю функции
в Point.cpp их определяем

https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%84%D0%B0%D0%B9%D0%BB#:~:text=h%3E%20%D0%B2%20%D0%A1%D0%B8).,%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0%20C%2B%2B%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D1%8E%D1%82%20%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20.

(крч это интерфейсы)

2020-10-17 15:10 UTC, SweetWeakness requested changes
проверьте на эти ошибки в кодсатйл весь свой код

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    vector<double> operator + (const vector<double>& left, const vector<double>& right) {
до и после operator+ пробел не нужен, дальше аналоигчно

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        int size_of_result_vector = left.size();
size_t

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        for(int i = 0; i < size_of_result_vector; ++ i) {
пробелы перед i не нужны

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        return fabs(result / size_of_result_vector - left[0] / right[0]) < eps;
так не сработает + можем поделить на ноль
(используйте проверку на косинус)

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        return (left || right) and left * right > 0;
а если вектор равны нулю?

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        int size;
size_t (везде в коде для size)

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        for(int i = 0; i < size; ++ i) input >> vec[i];
это не должно быть в одной стркое

2020-10-17 15:10 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        for (int i = 0; i < vec.size(); i++) out[i] = -vec[i];
анлогично

2020-10-18 07:22 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +    vector<double> operator + (const vector<double>& left, const vector<double>& right) {
[Исправлено](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/38d1b9400ec5d71cfeaed0bc81c3224d91a9a056)

2020-10-18 07:23 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +    vector<double> operator + (const vector<double>& left, const vector<double>& right) {
Почему нельзя поставить пробел до и после знака оператора?

2020-10-18 07:24 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        int size_of_result_vector = left.size();
Почему нужно использовать size_t?
[FIXED](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/0ec0b35c724a2e6427bd047f2290cd754d979c03)

2020-10-18 07:39 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        for(int i = 0; i < size; ++ i) input >> vec[i];
[FIXED](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/cf95f090189e5b1ebe20e30bf8abaebd863914d7)
Почему нельзя в одной строке?

2020-10-18 07:40 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        for (int i = 0; i < vec.size(); i++) out[i] = -vec[i];
Аналогично.

2020-10-18 07:40 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        int size;
Исправлено

2020-10-18 07:42 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        for(int i = 0; i < size_of_result_vector; ++ i) {
[FIXED](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/9b8e96673227b2c7ec83e291ebe24daba41a7395)

2020-10-18 07:53 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        return fabs(result / size_of_result_vector - left[0] / right[0]) < eps;
[FIXED](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/1bb251f22857b908740c08e52636c9a4867eba74)

2020-10-18 07:53 UTC, MAGLeb commented on vector_operations/src/vector_ops.h
> +        return (left || right) and left * right > 0;
[FIXED](https://github.com/MAGLeb/made-cpp-2020-hw/pull/3/commits/1bb251f22857b908740c08e52636c9a4867eba74)

2020-10-29 15:02 UTC, merged